### ISSUE TITLE
Not respecting Windows line endings

### ISSUE THREAD

**Issue by denolfe** [adzenith/CopyEdit#2]
Whenever I have this plugin enabled, and I copy out of Sublime into another app, the pasted text does not have any line returns.  I tested this by simply enabling/disabling the plugin and pasting into Notepad.

**Comment by adzenith** [comment]
Notepad doesn't respect Linux line endings, which is probably why you saw that problem there. I can change it so that it adds whatever line endings are being used in the file in question.

**Comment by denolfe** [comment]
That would be very helpful! I was pasting into another app's embedded editor, which is where I saw it first.  Looks like that app acts just as Notepad does. I appreciate the quick response.

**Comment by adzenith** [comment]
Try it now? I don't have a Windows machine at the moment so I can't make sure it works with Notepad specifically, but it seems to work.

**Comment by denolfe** [comment]
Works great for me, thanks!

**Comment by adzenith** [comment]
Glad to hear it!

**Comment by denolfe** [comment]
Hmm, it appears I spoke too early. Sublime may have had to be reopened?

**Comment by adzenith** [comment]
You mean it worked until you reopened, or it only worked once you reopened? Sublime has frequent and pervasive issues reloading preferences and plugins, so many times a restart is required even if it shouldn't be.

**Comment by denolfe** [comment]
I removed the old package, started Sublime, cloned master into my Packages folder, then tested.  After I restarted Sublime, the old behavior was back.  Looks like the package didn't take effect until I restarted.

**Comment by adzenith** [comment]
Hm, ok. I'll try and get my hands on a Windows computer so I can see what the problem is. Or maybe you should just use it on a Mac ;P

Out of curiosity, does it paste correctly into WordPad (or other non-Notepad apps)?

**Comment by denolfe** [comment]
The functionality is correct in WordPad as well as Microsoft Word 2013.

**Comment by adzenith** [comment]
Huh... does the file have Unix line endings or Windows line endings? I should probably base the copying on the system type rather than the file line endings.

**Comment by denolfe** [comment]
Hmm, I think it may have something to do with the file being open from the previous session. Once I closed the file's tab and reopened it, the functionality was correct. It looks to be working now.  Sorry for the back and forth! Thank you for your time as well.

**Comment by adzenith** [comment]
No problem! I think I might change it anyway—it probably won't work on files with Unix line endings.
