### ISSUE TITLE
What are the keys ?

### ISSUE THREAD

**Issue by ashishnegi** [adzenith/CopyEdit#3]
Hi 
Thanks for creating this plugin.
It would be great if you have some documentation about how to invoke your feature.
Especially after the install of your plugin.

As i am writing this i think i can go and look into your files but just to save others this problem.

**Comment by ashishnegi** [comment]
after reading the defalt key binding i found that they are not working and 
plugin is not listed in "Package Settings"

Mine is ST3 in ubuntu.

**Comment by adzenith** [comment]
The keys are just the default copy/paste keys. You don't have to do any extra binding.

**Comment by nicooprat** [comment]
Seems like it's working for regular Paste (thanks! ♥️), but not for Paste (CMD+V) + Paste and indent (CMD+SHIFT+V). Any idea?

**Comment by adzenith** [comment]
I'm not sure what you mean by regular Paste vs Paste (CMD+V). Can you elaborate? It doesn't right now work for paste and indent - is this something you'd like to see?

**Comment by nicooprat** [comment]
Wow, sorry, my sentence doesn't make any sense, I guess I was still asleep! Yes, I was thinking about "paste & indent". Would be cool indeed, even if this ST feature doesn't always work as expected...! Thanks :)
