### ISSUE TITLE
[Bug] Not working paste_from_history command

### ISSUE THREAD

**Issue by Kristinita** [adzenith/CopyEdit#4]
### Summary

If CopyEdit enable for me, `paste_from_history` default Sublime Text command not worked for me.

### Expected behavior

If CopyEdit disable for me:

![Expected](http://i.imgur.com/pw47xPc.png)

### Actual behavior

If CopyEdit enable for me, I don't saw menu under carriage.

### Steps to reproduce

The problem is reproduced for me in a version of Sublime Text without plugins and user settings.

In my text I copy `Sasha Unbelievable` → copy `Sasha Romantica` → `Edit` → `Paste From History` → I saw menu under carriage if CopyEdit disable for me and don't see menu if CopyEdit enable for me.

### Environment

**Operating system and version:**
Windows 32-bit 10.0.14393
**Sublime Text:**
Build 3126

Thanks.

**Comment by adzenith** [comment]
Unfortunately there's no way to plug into the paste history system. But what I could do is run the normal "copy" command while the replacement is running, which would populate that history with the result of a normal copy command. So you'd have a history as if you weren't using this plugin. Maybe still better than no history?

To try it out and see what I mean, apply this patch:

```
diff --git i/copy_edit.py w/copy_edit.py
index 1ee6e39a..3bed7ba6 100644
--- i/copy_edit.py
+++ w/copy_edit.py
@@ -38,6 +38,7 @@ class CopyEditCommand(sublime_plugin.TextCommand):
                        selection_strings[:] = [] #.clear() doesn't exist in 2.7
                        selection_strings.extend(new_sel_strings)
                        line_ending = line_endings[self.view.line_endings()]
+                       self.view.window().run_command("copy")
                        sublime.set_clipboard(line_ending.join(selection_strings))
                        return True
                return False
```

**Comment by Kristinita** [comment]
@adzenith — https://github.com/Kristinita/CopyEdit/blob/master/copy_edit.py#L37-L44. I correct insert patch? I do not understand, how I can paste from history even I use patch.

Thanks.

**Comment by adzenith** [comment]
Whoops! You were just supposed to insert the one line `self.view.window().run_command("copy")`. You can save the patch as a file and use "git apply" and it'll do the right thing. If it works for you let me know and I'll add it to master.

**Comment by Kristinita** [comment]
Thanks, it worked for me!

**Comment by alextretyak** [comment]
It does not worked for me. :(
Also, I suppose the right command is `self.view.run_command("copy")` (also not working).

**Comment by alextretyak** [comment]
It looks like [there is no way](https://forum.sublimetext.com/t/modifying-the-paste-from-history-list/15869) to affect “Paste from History” list from within plugins. :(
But inspired by @Jimbly's [SublimeClipboardHistory](https://github.com/Jimbly/SublimeClipboardHistory/blob/master/jimblys_clipboard_history.py) and @kemayo's [sublime-text-2-clipboard-history](https://github.com/kemayo/sublime-text-2-clipboard-history/blob/master/clipboard.py) plugins I have decided to implement/intergrate that logic into CopyEdit plugin, and also I'm going to fix one uncomfortable issue with Sublime that text copied to system clipboard outside of Sublime does not falls into Sublime “Paste from History” list! :)

**Comment by Jimbly** [comment]
Sounds great! (and this looks like a nice plugin =)

I was actually never able to get my SublimeClipboardHistory plugin working in ST3 (though some others reported that it worked for them, but maybe only in early beta), I always get - "ValueError: Edit objects may not be used after the TextCommand's run method has returned" because I'm trying to do an edit a couple seconds after the command is run (since it's in response to the menu of the history).  I'm not sure if there's a way around that, but I suspect you would need a workaround, so if you find one, please let me know =).

**Comment by alextretyak** [comment]
> @Jimbly 
"ValueError: Edit objects may not be used after the TextCommand's run method has returned" 

I have been also encountered this problem, but fortunately it can be fixed quite easily:

- In your case you can just replace `self.view.window().show_quick_panel` with `self.view.show_popup_menu`.

- Or, if you prefer `show_quick_panel`, then additional auxiliary text/view command should be added, for example:

```Python
class jch_kill_ring_insert_command(sublime_plugin.TextCommand):
    def run(self, edit, idx):
        jch_kill_ring.insert(self.view, edit, idx)
```

which can be called via this line of code:
```Python
self.view.window().show_quick_panel(names, lambda idx: self.view.run_command("jch_kill_ring_insert", {"idx": idx}))
```
this/\\line shoud be placed in place of
this\\/line of code:
```Python
self.view.window().show_quick_panel(names, functools.partial(jch_kill_ring.insert, self.view, edit))
```

**Comment by Jimbly** [comment]
show_popup_menu doesn't work well, doesn't respect any keybinds (e.g. vi navigational bindings, etc), the second works like a charm though, thanks a bunch!
