### ISSUE TITLE
[Bug] CopyEdit not worked if I overwrite hotkey for «paste» command

### ISSUE THREAD

**Issue by Kristinita** [adzenith/CopyEdit#6]
### Summary

CopyEdit not worked for me, if I overwrite hotkeys for `paste` command.

### Expected behavior

![Expected](https://camo.githubusercontent.com/3eb7cfc2a7351c397c3568240a0cde29f7f63b4b/687474703a2f2f692e696d6775722e636f6d2f773957506c59652e676966)

### Actual behavior

![Actual](http://i.imgur.com/qjavg5u.gif)

### Steps to reproduce

The problem is reproduced for me in a version of Sublime Text without plugins and user settings.

I add these lines in my `User/Default (Windows).sublime-keymap` file:

```json
{
    "keys": ["ctrl+v"],
    "command": "paste_and_indent"
}, {
    "keys": ["ctrl+shift+v"],
    "command": "paste"
},
```

I select multiple words → <kbd>Ctrl+C</kbd> → <kbd>Ctrl+Shift+V</kbd> or <kbd>Ctrl+V</kbd> → I'm not get expected behavior. In console, I see right commands for my hotkeys:

    key evt: control+v
    command: paste_and_indent
    key evt: shift+control+v
    command: paste

If I disable my shortcuts, I get expected behavior.

### Environment

**Operating system and version:**
Windows 32-bit 10.0.14393
**Sublime Text:**
Build 3126

Thanks.

**Comment by adzenith** [comment]
If you look at the keybindings file, you actually need to set the key to `paste_edit`.
Currently `paste_and_indent` isn't supported - is this something you'd like to see?

**Comment by Kristinita** [comment]
I'm sorry, I wrote incorrect issue. #7 is correct. Thanks.
