### ISSUE TITLE
[Feature request] CopyOnSelect plugin conflict

### ISSUE THREAD

**Issue by Kristinita** [adzenith/CopyEdit#7]
### Summary

If I use [CopyOnSelect](https://github.com/chrifpa/CopyOnSelect) plugin, CopyEdit not worked for me.

### Expected behavior

If CopyOnSelect disable for me:

![Expected](https://camo.githubusercontent.com/3eb7cfc2a7351c397c3568240a0cde29f7f63b4b/687474703a2f2f692e696d6775722e636f6d2f773957506c59652e676966)

### Actual behavior

If CopyOnSelect enable for me, not multiple cursors inserting, if I use `paste_edit` command.

### Steps to reproduce

The problem is reproduced for me in a version of Sublime Text without plugins and user settings.

I copy multiple fragments of text → <kbd>Ctrl+V</kbd> (`paste_edit`) → multiple cursors not inserted for me.

### Environment

**Operating system and version:**
Windows 32-bit 10.0.14393
**Sublime Text:**
Build 3126

Thanks.

**Comment by adzenith** [comment]
You would need to make copy_on_select call copy_edit instead of copy - otherwise it will fall back to the default behavior.
