### ISSUE TITLE
Copy/Paste multiple lines in "Column Selection mode"

### ISSUE THREAD

**Issue by stdedos** [adzenith/CopyEdit#9]
Selecting all the `Z`'s:

```
AAAA
BBBBZZZZZZZZZZ
CCCCZZZZZZZZZZ
DDDDZZZZZZZZZZ
EEEE
```
And then moving to a new file (i.e. one caret, empty file), pastes:
```
ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ
```

Whereas sometime you just want to extract a part from the middle of the lines
Is it possible it can be fixed?

Is it possible that we get a "CopyEdit Paste" command or a "Disable CopyEdit" shortcut?
I don't want to go to Package Manager for corner cases that Sublime can handle "better"

Operating system and version: Ubuntu 16.04.3
Sublime Text: Build 3143

**Comment by adzenith** [comment]
Yeah, you can just hit Enter after you paste and it'll put newlines after each pasted section. Let me know if that doesn't do what you want!
